# Generated by Django 4.0.1 on 2022-01-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(default='some ingredient', max_length=200, verbose_name='Название'),
        ),
    ]
