# Generated by Django 4.0.1 on 2022-01-04 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Введите название для публикации', verbose_name='Название')),
                ('image', models.ImageField(blank=True, help_text='Выбрать файл', null=True, upload_to='posts/', verbose_name='Изображение')),
                ('description', models.TextField(help_text='Введите текст публикации', verbose_name='Публикация')),
                ('coocking_time', models.CharField(help_text='Введите время приготовления блюда', max_length=30, verbose_name='Время приготовления')),
                ('author', models.ForeignKey(help_text='Выберите автора', on_delete=django.db.models.deletion.CASCADE, related_name='Recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор публикации')),
            ],
        ),
    ]
