# Generated by Django 4.0.1 on 2022-01-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
        ('recipe', '0005_remove_recipe_ingredients_recipe_ingredients_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='recipe',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipe.IngredientAmount', to='ingredient.Ingredient', verbose_name='ingredients'),
        ),
        migrations.DeleteModel(
            name='Amount',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='RecipeIngredient',
        ),
    ]
